default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: devise_2023_development
  port: 5433

test:
  <<: *default
  database: devise_2023_test
  port: 5433

production:
  <<: *default
  database: devise_2023_production
  username: devise_2023
  password: <%= ENV["BASE_PROJECT_2023_DATABASE_PASSWORD"] %>
